### ISSUE TITLE
Handling of unnecessary whitespace in core tiddlers

### ISSUE THREAD

**Issue by heronils** [Jermolene/TiddlyWiki5#3914]
For example, if, in an empty Wiki i create a Tiddler tagged with _$:/tags/Stylesheet_ and put the following css into it:

```css
.tc-tiddler-controls button, .tc-page-controls button {
    display:inline !important;
    margin:0 !important;
    padding:0 !important;
    width:32px !important;
    height:32px !important;
    border:1px solid green !important;
    vertical-align:middle !important;
    line-height:0 !important;
    font-size:0 !important;
}

.tc-tiddler-controls button svg, .tc-page-controls button svg {
    display:inline !important;
    margin:0 !important;
    padding:0 !important;
    width:32px !important;
    height:32px !important;
    border:1px solid orange !important;
    vertical-align:middle !important;
    line-height:0 !important;
    font-size:0 !important;
    line-height:32px !important;
    font-size:32px !important;
}
```

then the buttons will be normalized, mainly because of the `font-size:0;` hack. But there is still space between the buttons in the side bar on the right. I can fix that by setting the font size to 0 in the parent element too:

```css
.tc-tiddler-controls .tc-reveal, .tc-page-controls .tc-reveal {
    line-height:0 !important;
    font-size:0 !important;
}
```

There are [other methods](https://css-tricks.com/fighting-the-space-between-inline-block-elements/), but in general it would be nice if the html generated by TiddlyWiki is as compressed as possible, in order to avoid such surprises. This can mostly be done by removing those whitespaces in the core tiddlers. But a disadvantage is that these tiddlers can then not be nicely formatted.

It would therefore be nice to have a mechanism which strips those unnecessary white spaces automatically – when possible. But i dont know exactly how it could be done elegant. The block/inline rules for elements things like `<$x>...<$/x>`, `<<x>>` and `{{x}}` make it non trivial. At least i know what could be done after the parsing has happened:

1. replace `<element>\s*text\s*</element>` with `<element>text</element>` (i think tiddlywiki does this already). This also wont harm _pre_ s.
2. replace `\s*<npc>\s*` with `<npc>`

Here `<npc>` is the opening tag of a non phrasing content element – elements which are not allowed in paragraphs. Those elements are:

```
address, article, aside, blockquote, details, div, dl, fieldset,
figcaption, figure, footer, form, h1, h2, h3, h4, h5, h6,
header, hr, main, nav, ol, p, pre, section, table, ul
```

May be possible that i am missing some [other elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element) where we could do step 2.

The other cases would have to be manually hardcoded into the *.tids. For example we can not automatically decide case 2 for _button_ s or _span_ s, as they may appear in text. Those ambiguous elements should, if that is the intention, always be put without surrounding whitespaces into the *.tid. For example _core\ui\EditTemplate\controls.tid_ does it right, the _span_ s have no whitespace around them.
