### ISSUE TITLE
[IDEA] Small improvement to TiddlyWiki.com header bar

### ISSUE THREAD

**Issue by Arlen22** [Jermolene/TiddlyWiki5#4568]
I really like the header bar on tiddlywiki.com. I haven't upgraded to 5.1.22 yet, so I don't know whether this is a core feature or not, but here's a small styling improvement to it.

<img width="1440" alt="Screenshot 2020-04-16 14 21 38" src="https://user-images.githubusercontent.com/439872/79492272-be9a9580-7fed-11ea-8fba-d028b811051d.png">

Here's the tiddler CSS. Just add the `$:/tags/Stylesheet` tag.

```css
nav.tc-menubar li.tc-menubar-item svg {
    fill: #999;
}
nav.tc-menubar li.tc-menubar-item > a, nav.tc-menubar li.tc-menubar-item > button {
    color: #999;
}

nav.tc-menubar ul.tc-menubar-list {
    border-bottom: #cccccc;
    color: #999999;
    background: #f0f0f0;
    padding: 8px
}

@media (min-width: 960px) {
.tc-story-river {
    margin-top: 32px;
}
}
```
