### ISSUE TITLE
[BUG] Drag-and-drop onto empty story river doesn't import file(s)

### ISSUE THREAD

**Issue by jeremyredhead** [Jermolene/TiddlyWiki5#5446]
**Describe the bug**
Files or tiddlers won't be imported if drag & dropped onto an empty story river.
(some or all browsers may also try to navigate to said file(s))

**To Reproduce**
1. Go to https://tiddlywiki.com
2. Click on "close all" in the sidebar
3. Drag & drop files or tiddlers into the *middle* of the story river
4. Observe files or tiddlers not being imported

**Expected behavior**
Files and tiddlers will be imported no matter where/when I drop them.

**Cause of bug**
With no tiddlers in it, `.tc-story-river` shrinks to its *natural* minimum height (on my laptop, 84px).
The ancestor `.tc-dropzone` thus shrinks as well; importing is tied to drag&drop events on that element.
(*Note* that this bug can therefore crop up even if the story river isn't empty...)

**Proposed Fix(es)**
The simplest way to fix it would be tweaking the CSS somehow:

```css
/* assuming * { box-sizing: border-box }, or some such... */ 

/* forces a scrollbar on TW.com because of the menubar */
/* (the menubar css could be improved i think) */
.tc-story-river {
	min-height: 100vh;
}
/* == OR == */
/* someone else check this, i'm not 100% sure */
/* doesn't target other dropzones, i think */
.tc-page-container > .tc-dropzone {
	min-height: 100vh;
}
```

However, as I understand TW, the above approach would only fix the Vanilla/Snow White themes.
Other themes may or may not exhibit the same bug.
So another approach might be to move the `.tc-dropzone` somewhere else in the DOM, 
and then use min-height, z-index, [pointer-events], etc to style/position appropriately.
I'm not sure, someone else tell me if they think that's a bad idea or not.

[pointer-events]: https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events
