### ISSUE TITLE
[BUG] Markdown: Wrap table in HTML tags (p or div)

### ISSUE THREAD

**Issue by MaxGyver83** [Jermolene/TiddlyWiki5#6919]
### Describe the bug

Rendering error when table is wrapped into `div` or `p` tags (in Markdown tiddlers):

```
<div>

|   |   | DE | EN |
|---|---|----|----|
|17.| w |1,89 %|2,36 %|
|18.| f |1,66 %|2,23 %|

</div>
```

Output:

![image](https://user-images.githubusercontent.com/13970628/185737886-57a65b0a-9642-498a-a80a-86c81f8eded7.png)

### Expected behavior

No visible trailing `</div>`.

### Why I'm asking

Of course, a "naked" `div` around a table is not what I want.

One restriction of Markdown tiddlers is that `@@.classname` does not work there.

A simple workaround for simple things like a box around a paragraph:

Use

```md
<p class="red-box">
A paragraph.
</p>
```

instead of 

```
@@.red-box
A paragraph.
@@
```

Unwanted but harmless side effect: The paragraph with the red box gets wrapped into another paragraph.

To set a class for a table, you need to adapt your CSS rules. Example:

Replace

```css
table.striped-table tr:nth-child(odd){
  background-color: #f7f7f7;
}
table.striped-table tr:nth-child(even){
  background-color: #eee;
}
```

with 

```css
div.striped-table table tr:nth-child(odd){
  background-color: #f7f7f7;
}
div.striped-table table tr:nth-child(even){
  background-color: #eee;
}
```

Then I can use:

```
<div class="striped-table">

|my table|...

</div>
```

This works in WikiText tiddlers but not in Markdown tiddlers.

### To Reproduce

1. Create Markdown tiddler with this content
```
<div>

|   |   | DE | EN |
|---|---|----|----|
|17.| w |1,89 %|2,36 %|
|18.| f |1,66 %|2,23 %|

</div>
```

2. Check preview

### Screenshots

See above.

### TiddlyWiki Configuration

- Version: v5.2.3
- Saving mechanism: Node.js
- Plugins installed: Markdown

### Desktop (please complete the following information):

- OS: Arch Linux
- Browser: Firefox
- Version: 103.0.2 (64-bit)
