### ISSUE TITLE
[IDEA] Auto delete metafile of JSON plugin

### ISSUE THREAD

**Issue by linonetwo** [Jermolene/TiddlyWiki5#7741]
**Is your feature request related to a problem? Please describe.**

Sometimes a plugin was published with multi-tiddler format:

```json
{"tiddlers":{"$:/config/DownloadSaver/AutoSave":{"title":"$:/config/DownloadSaver/AutoSave","created":"20190601103555586","creator":"Lin Onetwo","modified":"20200410072837906","modifier":"Lin Onetwo","type":"text/vnd.tiddlywiki","text":"no"},"$:/config/MissingLinks":{"title":"$:/config/MissingLinks","created":"20190419034301891","modified":"20200409033736457","type":"text/vnd.tiddlywiki","text":"yes"},"$:/config/Navigation/UpdateAddressBar":{"title":"$:/config/Navigation/UpdateAddressBar","type":"text/vnd.tiddlywiki","text":"permaview"},"$:/config/Navigation/UpdateHistory":{"title":"$:/config/Navigation/UpdateHistory","created":"20190419034422400","modified":"20200409033736411","type":"text/vnd.tiddlywiki","text":"yes"},
```

with metafile

```yaml
author: LinOnetwo
core-version: >=5.1.22
dependents: $:/plugins/bimlas/locator $:/plugins/tiddlywiki/browser-sniff
description: Heavy lifting for new users to set up a powerful and opinionated knowledge management system.
list: readme description ControlPanel
name: ItonNote
plugin-type: plugin
title: $:/plugins/linonetwo/itonnote
type: application/json
version: 1.1.4
```

And later it is upgrade to use JSON tiddler format:

```json
[
    {
        "author": "LinOnetwo",
        "core-version": ">=5.1.22",
        "dependents": "$:/plugins/tiddlywiki/browser-sniff",
        "description": "Heavy lifting for new users to set up a powerful and opinionated knowledge management system.",
        "list": "readme description ControlPanel",
        "name": "ItonNote",
        "plugin-type": "plugin",
        "text": "{\"tiddlers\":{\"$:/config/DownloadSaver/AutoSave\":{\"title\":\"$:/config/DownloadSaver/AutoSave\",\"created\":\"20190601103555586\",\"creator\":\"Lin Onetwo\",\"modified\":\"20200410072837906\",\"modifier\":\"Lin Onetwo\",\"type\":\"text/vnd.tiddlywiki\",\"text\":\"no\"},\"$:/config/MissingLinks\":{\"title\":\"$:/config/MissingLinks\",\"created\":\"20190419034301891\",\"modified\":\"20200409033736457\",\"type\":\"text/vnd.tiddlywiki\",\"text\":\"yes\"},
```

Then the existing metafile will prevent its content for properly loaded

![图片](https://github.com/Jermolene/TiddlyWiki5/assets/3746270/c2ddc94b-d543-4526-8f9f-7c408943eaa4)

**Describe the solution you'd like**

When upgrading a plugin, consider its format, and delete relevant metafile.

**Describe alternatives you've considered**

Or show a friendly error message on empty plugins (but with `plugin size: 43.5 k characters (43519)` it can't really be empty) to ask user to manually delete the .meta file

![图片](https://github.com/Jermolene/TiddlyWiki5/assets/3746270/206e8474-35b5-458f-b1bf-b8c6fa714857)

**Additional context**

The old multi-tiddler format was generated by https://github.com/tiddly-gittly/TiddlyWiki-TS-Plugin-Template 
And new JSON format is generated by https://github.com/tiddly-gittly/Modern.TiddlyDev
